name: Healthview
version: ${project.version}
main: com.toke1597.healthview.Healthview
api-version: 1.15
authors: [toke1597]
description: Health
commands:
  healthview:
    description: Toggle healthview!
